@extends('layouts.admin-auth',['title'=>'Admin Login'])
@section('content')
    @include('auth.admin.partials.loginForm',['data' => ''])
    @include('auth.admin.partials.twoFactorAuthenticationForm',['data' => 'display:none;'])
@stop
@push('js')
   <script>
       function validation1add(){""==$("#phone").val()?($("#phone").css("border","2px solid red"),$("#phone").css("background-image","none"),Toast.fire({icon:"error",title:"Enter your phone"})):$("#phone").css("border","1px solid #ced4da")}function validation2add(){if(""==$("#password").val()){$("#password").css("border","2px solid red"),$("#password").css("background-image","none"),""!=$("#phone").val()&&Toast.fire({icon:"error",title:"Enter your password"})}else $("#password").css("border","1px solid #ced4da")}function loginerror(){clear(),Toast.fire({icon:"error",title:"These credentials do not match."})}function clear(){$(".ms-bar-login").removeClass("ms-bar"),$(".ms-blur-bg").css("filter","blur(0px)"),document.getElementById("btn-login-admin").disabled=!1,$(".invalid-feedback3").css("display","inline-block")}function account_verify(){swalWithBootstrapButtons.fire("Your Account is Not Verify:)","Please Verify Now","error")}function account_suspend(){swalWithBootstrapButtons.fire("Your Account is InActive:)","Please Contact Admin","error"),clear(),$(".invalid-feedback3").css("display","none"),$("#phone").val(""),$("#password").val("")}$(".btn-login-admin").click(function(){validation1add(),validation2add();var e=$("#phone").val(),o=$("#password").val(),n="";n=$("input[type='checkbox'].remember").is(":checked")?"remember":"",""==e||""==o||($(".ms-bar-login").addClass("ms-bar"),$(".ms-blur-bg").css("filter","blur(5px)"),document.getElementById("btn-login-admin").disabled=!0,$(".invalid-feedback3").css("display","none"),$.ajax({headers:{"X-CSRF-TOKEN":$('meta[name="csrf-token"]').attr("content")},type:"post",dataType:"json",url:"/admin-server/login/check-points",data:{phone:e,password:o,remember:n},success:function(n){setTimeout(function(){8606===n?(Toast.fire({icon:"warning",title:"Two Factor Authentication"}),setTimeout(function(){clear(),$("#last3DigitPhone").text("(xxx)-xxx-"+e.replace(/\d(?=\d{4})/g,"")),$("#loginForm").css("display","none"),$("#twoFactorAuthenticationForm").css("display","-webkit-box"),$("#phone").val(e),$("#password").val(o)},3e3)):200===n?(Toast.fire({icon:"success",title:"You are successfully login:)"}),setTimeout(function(){window.open("/admin/dashboard","_self")},1e3)):8605===n?(account_verify(),setTimeout(function(){window.open("?account-verify=true&u="+e,"_self")},3e3)):8604===n?account_suspend():404===n&&setTimeout(function(){loginerror()},1e3)},1e3)},error:function(){location.reload()}}))});
   </script>
@endpush

